name: docker
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build/Push docker containers
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - uses: actions/checkout@v2
      - name: Login to GitHub Packages Docker Registry
        uses: docker/login-action@v1
        with:
          registry: docker.pkg.github.com
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -t docker.pkg.github.com/yajm/migrosdreamteam/search-api .
      - run: docker push docker.pkg.github.com/yajm/migrosdreamteam/search-api
